apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuber-set
  labels:
    ver: v1.1
    app: alpaca
    env: prod
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      ver: v1.1
      app: alpaca
      env: prod
  template:
    metadata:
      labels:
        ver: v1.1
        app: alpaca
        env: prod
    spec:
      containers:
      - name: php-redis
        image: ekke020/kuber:1.1
